### ISSUE TITLE
Review the design of the VM component

### ISSUE THREAD

**Issue by cfsnyder** [ilanddev/gibraltar#21]
A design review is required for the existing VM component implementation. You can view the current implementation in the demo project here: https://deploy-preview-24--objective-easley-d75b69.netlify.com/

**Comment by mathieupkf** [comment]
@cfsnyder - good for me, just minor feedbacks:
- Use 10 px margin between each component. 
- I've adjusted VM library icons. Let me know if you need specific exports. https://projects.invisionapp.com/d/main#/console/12026582/359133695/preview

**Comment by cfsnyder** [comment]
@mathieupkf - the margins aren't really relevant to the VM component, they're just arbitrary for the demo, but I'll update the demo to space them at 10px anyways. I'll need each of those icons individually exported as an SVG and I'll need them updated so that only the left-side corners are rounded.

**Comment by mathieupkf** [comment]
@cfsnyder - 
- I knew it but I thought that it will be better to have those components with right paddings, to see them in a good environment ;) Not a big deal.
- You can download SVG files with right corners directly from the InVision link
